Add files via upload
AgP42/suiviCO2 pull request #4
Opened 2020-05-09 12:06 UTC by fbell58

le fichier au bon endroit ... desolé je maitrise pas git hub

2020-05-09 18:12 UTC, AgP42 requested changes
Merci pour ces modifs, plusieurs points ne sont pas clairs pour moi. Notamment pourquoi décaler la date de 1h et non pas juste de 5min et n'est-ce pas faire un double décalage que de décaler aussi la date pour le calcul des totaux ? Merci pour vos réponses ! ;-)

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +        if ($consumption < 15 * 1000) { //13 kWh pour compteur 63 A  par heure c'est qu'on a un gros probleme... Ce test permet de ne pas sauvegarder l'index entier lors de la 1ere boucle apres la cr
A la limite on pourrait complètement supprimer ce test... La valeur "max" dépend pas mal de l'installation de chacun. J'avais finalement mis 1000 * 1000 dans l'actuelle beta pour garder l'esprit d'origine de cette boucle qui voulait juste tronquer l'index total lors de la création de l'équipement

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +                $cmd->setCollectDate($_datetime_data);
Finalement ça sert à quelque chose ? Si non, autant virer cette ligne. 
A tester sans ?

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +            $cmdTotalDay->setCollectDate($_datetime_data);
idem, à commenter et tester sans cette ligne pour voir si elle sert vraiment à quelque chose ?

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +    public static function suiviCO2hourly()
Pas compris cette fonction, mais à virer maintenant, non ?

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +        $datetime_data = date('Y-m-d H:i:00', time() - 3600);
là on décale pas d'1 min mais d'1h. Pourquoi pas juste de 5 min comme discuté par mail ?

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +            $cmdTotalMonth->setCollectDate($_datetime_data);
idem, à supprimer ?

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +            $cmdTotalMonth->event($totalCO2, $_datetime_data);
Est-ce que décaler aussi la date pour les totaux ne revient pas à un double décalage car il va faire son calcul sur des données déjà décalées, non ?
Par ailleurs avez vous vérifié si les infos sur le dashboard étaient toujours actualisées et correcte ?

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +            $cmdTotalWeek->setCollectDate($_datetime_data);
idem, à supprimer ?

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +            $cmdTotalWeek->event($totalCO2, $_datetime_data);
idem remarque sur cmdTotalMonth

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +            $cmdTotalDay->event($totalCO2, $_datetime_data);
idem remarque sur cmdTotalMonth

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +            $suiviCO2->calculTotauxCo2($datetime_data);
voir ma remarque sur cmdTotalMonth, est-ce qu'on ne décale pas 2 fois en enregistrant aussi les totaux à une date décalée alors qu'ils vont deja être calculé sur des datas en DB décalées d'1h ?

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +                            $cmd->setCollectDate($datetime_data);
Je comprends pas pourquoi avoir ajouté cette variable et ce setCollectDate ici

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +                            $cmd->event($record_tauxco2);
Si vous voulez aussi changer la date pour cette fonction, pourquoi ne pas l'ajouter ici en second argument ?

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +            $suiviCO2->calculConso('HP', $datetime_data);
ok

2020-05-09 18:12 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +                $suiviCO2->calculConso('HC', $datetime_data);
ok

2020-05-11 20:21 UTC, fbell58 commented on core/class/suiviCO2.class.php
> +        if ($consumption < 15 * 1000) { //13 kWh pour compteur 63 A  par heure c'est qu'on a un gros probleme... Ce test permet de ne pas sauvegarder l'index entier lors de la 1ere boucle apres la cr
oui j ai mis 15 car j ai abonnement de 13 KW donc je peux pas consommer plus que ca ...mais comme j ai pas bien compris pourquoi il y avait le test j ai laissé mais pour moi c est inutile

a vous de voir si il faut le concerver mais maintenant avec 1000 kw par heure le test sera toujours ok !!!!!

2020-05-11 20:21 UTC, fbell58 commented on core/class/suiviCO2.class.php
> +                $cmd->setCollectDate($_datetime_data);
e pense que ca sert a rien surtout que a l origine vous aviez mis

$cmd->setCollectDate($_datetime);  et  $datetime etait pas initialisé
 j ai verifier a l execussion ...donc inutile effectivement et phpstorm indiquait une variable inconnue !!!

2020-05-11 20:22 UTC, fbell58 commented on core/class/suiviCO2.class.php
> +            $cmdTotalDay->setCollectDate($_datetime_data);
j ai testé sans les lignes $cmdTotalDay->setCollectDate($datetime);   depuis dimanche et c est OK

2020-05-11 20:23 UTC, fbell58 commented on core/class/suiviCO2.class.php
> +    public static function suiviCO2hourly()
techniquement elle sert a rien mais si on la declare dans le moteur des taches c est tres pratique pour faire des tests sans avoir a attendre une heure je fais comme ca je sais pas comment vous faite ordinairement pour tester sans attendre une heure 



vous lancer la tache a la main et hop....

2020-05-11 20:24 UTC, fbell58 commented on core/class/suiviCO2.class.php
> +        $datetime_data = date('Y-m-d H:i:00', time() - 3600);
inalement j ai decalé de 1heure car j ai vu un momment que vous faisiez un test sur les enregistrement a l heure juste

et j ai l impression que d avoir les valeurs a 55 ca marchais plus du coup d ou le decalage a 00 de l heure d avant j ai plus de pb sur la consoC02 du coup !!!


_// on filtre sur les heures piles
if (date('i', strtotime($valueDateTimeAPI)) == "00") { // on extrait le champ min et on verifie qu'il vaut 00_

2020-05-11 20:25 UTC, fbell58 commented on core/class/suiviCO2.class.php
> +            $suiviCO2->calculTotauxCo2($datetime_data);
mes info sur dashboard me semble correcte mais il faut attendre 1 jour complet et il faudrait faire un calcul a la main pour verivier le volume de CO2 

verifié depuis ok voir le fichier excel sur le forum jeedom que j ai mis pour vous dans mon message de Dimanche

2020-05-11 20:26 UTC, fbell58 commented on core/class/suiviCO2.class.php
> +                            $cmd->setCollectDate($datetime_data);
> idem remarque sur cmdTotalMonth  oui toute les lignes
> $cmdTotalWeek->setCollectDate($_datetime_data);


sont inutiles je pense si elel sont suivi par un event c est justement cette commande qui est faite par event.....

j avais mis ca pour corriger le fait que la donnée etait pas initialisée mais apres test les 2 lignes ne servent a rien

2020-05-11 20:27 UTC, fbell58 commented on core/class/suiviCO2.class.php
> +                            $cmd->event($record_tauxco2);
a oublier

2020-05-11 20:28 UTC, fbell58 commented on core/class/suiviCO2.class.php
> +                            $cmd->event($record_tauxco2);
la on change pas j ai pas touché ca il me semble la on a pas de decalage c est ce qui est recupéré du net donc ... et si on passe pas de second arguments a event il prend la date de l appel je pense c est juste avant que je comprenne c etait pour corriger $datetime qui etait pas initialisé !!!!!

2020-05-11 20:29 UTC, fbell58 commented on core/class/suiviCO2.class.php
> +                            $cmd->setCollectDate($datetime_data);
ca c est une erreur de ma part ...désolé il sert a rien

2020-05-12 08:17 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +        if ($consumption < 15 * 1000) { //13 kWh pour compteur 63 A  par heure c'est qu'on a un gros probleme... Ce test permet de ne pas sauvegarder l'index entier lors de la 1ere boucle apres la cr
Justement, l'idée de cette boucle c'est de filtrer le tout premier calcul de conso qui va donc être l'index entier du compteur. Sinon quand on crée l'équipement on a toute la conso des années passées, chez moi c'est 28600000wh. Je vais laisser 1000 kwh.

2020-05-12 08:20 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +                $cmd->setCollectDate($_datetime_data);
$datetime n'est pas inconnu chez moi, meme s'il n'était pas passé en argument, il était `$datetime = date('Y-m-d H:i:00');`.
Mais ok je vais virer cette ligne partout aussi vu que c'est écrasé par la fonction event

2020-05-12 08:23 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +    public static function suiviCO2hourly()
je déclenche juste manuellement le cronHourly dans le moteur de tâche... (Ce qui le déclenche donc pour tous les plugins l'utilisant, c'est pas forcement très propre mais c'est un jeedom de développement de toute façon...)

2020-05-12 08:24 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +        $datetime_data = date('Y-m-d H:i:00', time() - 3600);
ok

2020-05-12 08:25 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +            $suiviCO2->calculTotauxCo2($datetime_data);
ok parfait

2020-05-12 08:25 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +                            $cmd->setCollectDate($datetime_data);
ok

2020-05-12 08:26 UTC, AgP42 commented on core/class/suiviCO2.class.php
> +                            $cmd->event($record_tauxco2);
ok

2020-05-12 11:06 UTC, fbell58 commented on core/class/suiviCO2.class.php
> +                $cmd->setCollectDate($_datetime_data);
on peut le retirer ca marche sans ..

et pour moi il est defini au niveau de cronhourly et si il est pas passé en parametre il est hors scop dans les subroutines ???
J ai essayer de l imprimer dans un log et il est vide pas de valeur ...

2020-05-12 11:07 UTC, fbell58 commented on core/class/suiviCO2.class.php
> +            $cmdTotalMonth->setCollectDate($_datetime_data);
oui a supprimer selon moi

2020-05-12 12:32 UTC, AgP42 commented
Comme dit par mail, je clos cette PR sans la merger à cause des corrections qui seraient encore à apporter et à cause de la remise en forme qui rend tout diff illisible, mais j'ai pris en compte les propositions dans la beta 2.0.5. 

Merci !

2020-05-12 12:32 UTC, closed without merging